In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

:

In [4]:
housing = pd.read_csv("./housing.csv")

In [5]:
housing['income_cat'] = pd.cut(housing['median_income'], bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf], labels=[1, 2, 3, 4, 5])

In [6]:
housing.head()

   longitude  latitude  housing_median_age  total_rooms  ...  median_income  median_house_value  ocean_proximity  income_cat
0    -122.23     37.88                41.0        880.0  ...         8.3252            452600.0         NEAR BAY           5
1    -122.22     37.86                21.0       7099.0  ...         8.3014            358500.0         NEAR BAY           5
2    -122.24     37.85                52.0       1467.0  ...         7.2574            352100.0         NEAR BAY           5
3    -122.25     37.85                52.0       1274.0  ...         5.6431            341300.0         NEAR BAY           4
4    -122.25     37.85                52.0       1627.0  ...         3.8462            342200.0         NEAR BAY           3

[5 rows x 11 columns]

In [7]:
from sklearn.model_selection import StratifiedShuffleSplit

In [8]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in sss.split(housing, housing['income_cat']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [9]:
# removing income_cat column
for strat_sets in (strat_test_set, strat_train_set):
    strat_sets.drop("income_cat", axis=1, inplace=True)

In [10]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
#  we can use any other strategy like mean, most-freq etc
imputer = SimpleImputer(strategy='median')

In [13]:
housing_num = housing.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [14]:
#  This computes the median for each numerical column and stores it in imputer.statistics_:
imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [15]:
X = imputer.transform(housing_num)

In [16]:
X

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]], shape=(16512, 8))

In [17]:
housing = pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [18]:
housing['ocean_proximity'] = strat_train_set['ocean_proximity']
housing

       longitude  latitude  housing_median_age  total_rooms  ...  population  households  median_income  ocean_proximity
12655    -121.46     38.52                29.0       3873.0  ...      2237.0       706.0         2.1736           INLAND
15502    -117.23     33.09                 7.0       5320.0  ...      2015.0       768.0         6.3373       NEAR OCEAN
2908     -119.04     35.37                44.0       1618.0  ...       667.0       300.0         2.8750           INLAND
14053    -117.13     32.75                24.0       1877.0  ...       898.0       483.0         2.2264       NEAR OCEAN
20496    -118.70     34.28                27.0       3536.0  ...      1837.0       580.0         4.4964        <1H OCEAN
...          ...       ...                 ...          ...  ...         ...         ...            ...              ...
15174    -117.07     33.03                14.0       6665.0  ...      2026.0      1001.0         5.0900        <1H OCEAN
12661    -121.42     38.51                15.0       7901.0  ...      4769.0      1418.0         2.8139           INLAND
19263    -122.72     38.44                48.0        707.0  ...       458.0       172.0         3.1797        <1H OCEAN
19140    -122.70     38.31                14.0       3155.0  ...      1208.0       501.0         4.1964        <1H OCEAN
19773    -122.14     39.97                27.0       1079.0  ...       625.0       197.0         3.1319           INLAND

[16512 rows x 9 columns]

In [23]:
housing_cat = housing[['ocean_proximity']]

In [24]:
housing_cat.head()

      ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [26]:
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)

In [28]:
# ton see the mapping
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
one_hot_encoder = OneHotEncoder()
housing_cat_1hot = one_hot_encoder.fit_transform(housing_cat)

In [38]:
one_hot_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [39]:
# This gives a sparse matrix (efficient storage for mostly zeros).
#  so we have to convert it to a regular NumPy array:
housing_cat_1hot.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], shape=(16512, 5))

In [41]:
housing_cat_1hot_df = pd.DataFrame(housing_cat_1hot.toarray() , columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'] ,index=housing.index)

In [ ]:
housing_cat_1hot_df

### Now from here we are starting feature scaling

In [48]:
new_housing = pd.concat([housing, housing_cat_1hot_df], axis=1)
new_housing = new_housing.drop('ocean_proximity', axis=1)
new_housing

       longitude  latitude  housing_median_age  total_rooms  ...  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655    -121.46     38.52                29.0       3873.0  ...     1.0     0.0       0.0         0.0
15502    -117.23     33.09                 7.0       5320.0  ...     0.0     0.0       0.0         1.0
2908     -119.04     35.37                44.0       1618.0  ...     1.0     0.0       0.0         0.0
14053    -117.13     32.75                24.0       1877.0  ...     0.0     0.0       0.0         1.0
20496    -118.70     34.28                27.0       3536.0  ...     0.0     0.0       0.0         0.0
...          ...       ...                 ...          ...  ...     ...     ...       ...         ...
15174    -117.07     33.03                14.0       6665.0  ...     0.0     0.0       0.0         0.0
12661    -121.42     38.51                15.0       7901.0  ...     1.0     0.0       0.0         0.0
19263    -122.72     38.44                48.0        707.0  ...     0.0     0.0       0.0         0.0
19140    -122.70     38.31                14.0       3155.0  ...     0.0     0.0       0.0         0.0
19773    -122.14     39.97                27.0       1079.0  ...     1.0     0.0       0.0         0.0

[16512 rows x 13 columns]

In [49]:
from sklearn.preprocessing import MinMaxScaler

In [55]:
min_max_scaler = MinMaxScaler(feature_range=(-1,1))
housing_min_max_scaled = min_max_scaler.fit_transform(new_housing)

In [60]:
housing_min_max_scaled = pd.DataFrame(housing_min_max_scaled, columns=new_housing.columns, index=new_housing.index)

In [61]:
housing_min_max_scaled

       longitude  latitude  housing_median_age  total_rooms  ...  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655  -0.424303  0.270988            0.098039    -0.803276  ...     1.0    -1.0      -1.0        -1.0
15502   0.418327 -0.883103           -0.764706    -0.729664  ...    -1.0    -1.0      -1.0         1.0
2908    0.057769 -0.398512            0.686275    -0.917994  ...     1.0    -1.0      -1.0        -1.0
14053   0.438247 -0.955367           -0.098039    -0.904818  ...    -1.0    -1.0      -1.0         1.0
20496   0.125498 -0.630181            0.019608    -0.820420  ...    -1.0    -1.0      -1.0        -1.0
...          ...       ...                 ...          ...  ...     ...     ...       ...         ...
15174   0.450199 -0.895855           -0.490196    -0.661240  ...    -1.0    -1.0      -1.0        -1.0
12661  -0.416335  0.268863           -0.450980    -0.598362  ...     1.0    -1.0      -1.0        -1.0
19263  -0.675299  0.253985            0.843137    -0.964338  ...    -1.0    -1.0      -1.0        -1.0
19140  -0.671315  0.226355           -0.490196    -0.839803  ...    -1.0    -1.0      -1.0        -1.0
19773  -0.559761  0.579171            0.019608    -0.945414  ...     1.0    -1.0      -1.0        -1.0

[16512 rows x 13 columns]

### Now as above mwthod is sensitive to outliers (extreme values can distort the scale).sow e will use another method in such cases which is Standardization (Z-score Scaling)

- it uses fromula 
            `Standardization (Z-score Scaling)`
            
- while above method uised formula 
            `scaled_value = (x - min) / (max - min)`

In [65]:
from sklearn.preprocessing import StandardScaler

In [69]:
std_scaler = StandardScaler()
housing_std_scaled = std_scaler.fit_transform(new_housing)

In [70]:
housing_std_scaled

array([[-0.94135046,  1.34743822,  0.02756357, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [ 1.17178212, -1.19243966, -1.72201763, ..., -0.0110063 ,
        -0.3548889 ,  2.60269309],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.0110063 ,
        -0.3548889 , -0.38421741],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.0110063 ,
        -0.3548889 , -0.38421741]], shape=(16512, 13))

In [71]:
housing_std_scaled = pd.DataFrame(housing_std_scaled, columns=new_housing.columns, index=new_housing.index)

In [72]:
housing_std_scaled

       longitude  latitude  housing_median_age  total_rooms  ...   INLAND    ISLAND  NEAR BAY  NEAR OCEAN
12655  -0.941350  1.347438            0.027564     0.584777  ...  1.46218 -0.011006 -0.354889   -0.384217
15502   1.171782 -1.192440           -1.722018     1.261467  ... -0.68391 -0.011006 -0.354889    2.602693
2908    0.267581 -0.125972            1.220460    -0.469773  ...  1.46218 -0.011006 -0.354889   -0.384217
14053   1.221738 -1.351474           -0.370069    -0.348652  ... -0.68391 -0.011006 -0.354889    2.602693
20496   0.437431 -0.635818           -0.131489     0.427179  ... -0.68391 -0.011006 -0.354889   -0.384217
...          ...       ...                 ...          ...  ...      ...       ...       ...         ...
15174   1.251711 -1.220505           -1.165333     1.890456  ... -0.68391 -0.011006 -0.354889   -0.384217
12661  -0.921368  1.342761           -1.085806     2.468471  ...  1.46218 -0.011006 -0.354889   -0.384217
19263  -1.570794  1.310018            1.538566    -0.895802  ... -0.68391 -0.011006 -0.354889   -0.384217
19140  -1.560803  1.249211           -1.165333     0.249005  ... -0.68391 -0.011006 -0.354889   -0.384217
19773  -1.281050  2.025674           -0.131489    -0.721836  ...  1.46218 -0.011006 -0.354889   -0.384217

[16512 rows x 13 columns]