In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

:

In [103]:
housing = pd.read_csv("./housing.csv")

In [104]:
housing['income_cat'] = pd.cut(housing['median_income'], bins=[0, 1.5, 3.0, 4.5, 6.0, np.inf], labels=[1, 2, 3, 4, 5])

In [105]:
housing.head()

   longitude  latitude  housing_median_age  total_rooms  ...  median_income  median_house_value  ocean_proximity  income_cat
0    -122.23     37.88                41.0        880.0  ...         8.3252            452600.0         NEAR BAY           5
1    -122.22     37.86                21.0       7099.0  ...         8.3014            358500.0         NEAR BAY           5
2    -122.24     37.85                52.0       1467.0  ...         7.2574            352100.0         NEAR BAY           5
3    -122.25     37.85                52.0       1274.0  ...         5.6431            341300.0         NEAR BAY           4
4    -122.25     37.85                52.0       1627.0  ...         3.8462            342200.0         NEAR BAY           3

[5 rows x 11 columns]

In [106]:
from sklearn.model_selection import StratifiedShuffleSplit

In [107]:
sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in sss.split(housing, housing['income_cat']):
    strat_train_set = housing.loc[train_index]
    strat_test_set = housing.loc[test_index]

In [108]:
# removing income_cat column
for strat_sets in (strat_test_set, strat_train_set):
    strat_sets.drop("income_cat", axis=1, inplace=True)

In [109]:
housing = strat_train_set.drop("median_house_value", axis=1)
housing_labels = strat_train_set["median_house_value"].copy()

In [110]:
housing = housing.drop('ocean_proximity', axis=1)

In [111]:
housing

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  population  households  median_income
12655    -121.46     38.52                29.0       3873.0           797.0      2237.0       706.0         2.1736
15502    -117.23     33.09                 7.0       5320.0           855.0      2015.0       768.0         6.3373
2908     -119.04     35.37                44.0       1618.0           310.0       667.0       300.0         2.8750
14053    -117.13     32.75                24.0       1877.0           519.0       898.0       483.0         2.2264
20496    -118.70     34.28                27.0       3536.0           646.0      1837.0       580.0         4.4964
...          ...       ...                 ...          ...             ...         ...         ...            ...
15174    -117.07     33.03                14.0       6665.0          1231.0      2026.0      1001.0         5.0900
12661    -121.42     38.51                15.0       7901.0          1422.0      4769.0      1418.0         2.8139
19263    -122.72     38.44                48.0        707.0           166.0       458.0       172.0         3.1797
19140    -122.70     38.31                14.0       3155.0           580.0      1208.0       501.0         4.1964
19773    -122.14     39.97                27.0       1079.0           222.0       625.0       197.0         3.1319

[16512 rows x 8 columns]

In [112]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [113]:
housing_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("standardize", StandardScaler()),
])

#! If you don't want to name the steps manually, you can use make_pipeline():

In [114]:
housing_pipeline.fit_transform(housing)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.73260236,
         0.55628602, -0.8936472 ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.53361152,
         0.72131799,  1.292168  ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.67467519,
        -0.52440722, -0.52543365],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.86201341,
        -0.86511838, -0.36547546],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.18974707,
         0.01061579,  0.16826095],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.71232211,
        -0.79857323, -0.390569  ]], shape=(16512, 8))